routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',function (){
    return view('errors.404');
});
Route::any('captcha-test', function()
{
    if (Request::getMethod() == 'POST')
    {
        $rules = ['captcha' => 'required|captcha'];
        $validator = Validator::make(Input::all(), $rules);
        if ($validator->fails())
        {
            echo '<p style="color: #ff0000;">Incorrect!</p>';
        }
        else
        {
            echo '<p style="color: #00ff30;">Matched :)</p>';
        }
    }

    $form = '<form method="post" action="captcha-test">';
    $form .= '<input type="hidden" name="_token" value="' . csrf_token() . '">';
    $form .= '<p>' . captcha_img() . '</p>';
    $form .= '<p><input type="text" name="captcha"></p>';
    $form .= '<p><button type="submit" name="check">Check</button></p>';
    $form .= '</form>';
    return $form;
});
Route::get('/get_captcha/{config?}', function (\Mews\Captcha\Captcha $captcha, $config = 'default') {
    return $captcha->src($config);
});
/********operators routes*************/
// Authentication Routes...
Route::get('login', [
    'as' => 'login',
    'uses' => 'AuthController@login'
]);
Route::post('check_login', [
    'as' => 'check_login',
    'uses' => 'AuthController@check_login'
]);
//route::post('chech_user')

/*Route::post('login', [
    'as' => '',
    'uses' => 'Auth\LoginController@login'
]);*/
/*Route::post('logout', [
    'as' => 'logout',
    'uses' => 'AuthController@logout'
]);*/
Route::get('logout', [
    'as' => 'logout',
    'uses' => 'AuthController@logout'
]);

/*Route::get('register', [
    'as' => 'register',
    'uses' => 'AuthController@register'
]);
Route::post('register', [
    'as' => 'check_register',
    'uses' => 'AuthController@check_register'
]);*/


// Password Reset Routes...
Route::post('password/email', [
    'as' => 'password.email',
    'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail'
]);
Route::get('password/reset', [
    'as' => 'password.request',
    'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm'
]);
Route::post('password/reset', [
    'as' => '',
    'uses' => 'Auth\ResetPasswordController@reset'
]);
Route::get('password/reset/{token}', [
    'as' => 'password.reset',
    'uses' => 'Auth\ResetPasswordController@showResetForm'
]);

// Registration Routes...

/*
Route::group(['domain'=>'xbody'],function (){
    //site index route
    Route::get('/', function (){
        return view('index_page');
    })->name('home');
    Route::get('/home', 'HomeController@home')->name('home2');
    Route::get('/exchange', 'HomeController@exchange')->name('exchange');
  Route::get('/product/{product}','ProductController@show')->name('product.show');

});*/

//home routs
Route::get('/','HomeController@index')->name('home');
Route::get('page/{page}','PageController@show')->name('page');
//admin route group
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function()
{
    Route::get('/','AdminController@admin_panel')->name('admin');
    route::resource('admin','AdminController',['except'=>['destroy']]);
    Route::post('admin/socials',['as'=>'socials','uses'=>'HomeController@socials']);
    Route::post('admin/config',['as'=>'config','uses'=>'HomeController@config']);

    // Registration Routes...
    Route::get('/register',['as'=>'register','uses'=> 'AdminAuth\RegisterController@showRegistrationForm']);
    Route::post('/register',['as'=>'register','uses'=> 'AdminAuth\RegisterController@register']);
    //Login Routes...
    Route::get('/login',['as'=>'login','uses'=>'AdminAuth\LoginController@showLoginForm']);
    Route::post('/login',['as'=>'login','uses'=>'AdminAuth\LoginController@login']);
    Route::get('/logout',['as'=>'logout','uses'=>'AdminAuth\LoginController@logout']);


//admin.attribute.group routes
    Route::resource('attribute-group', 'AttributeGroupController', ['except' => ['destroy']]);
    Route::Delete('/attribute-group/destroy',['as'=>'attribute-group.destroy','uses'=>'AttributeGroupController@destroy']);
//admin.attribute routes
    Route::resource('attribute', 'AttributeController', ['except' => ['destroy']]);
    Route::Delete('/attribute/destroy',['as'=>'attribute.destroy','uses'=>'AttributeController@destroy']);

    Route::get('setting','AdminController@setting_index')->name('setting');
    Route::patch('setting','AdminController@setting')->name('setting.update');

//admin.product routes
    Route::resource('product', 'ProductController', ['except' => ['destroy']]);
    Route::Delete('/product/destroy',['as'=>'product.destroy','uses'=>'ProductController@destroy']);
    Route::post('/product/slug',['as'=>'product.slug','uses'=>'ProductController@slug']);
    Route::Post('/product/filter',['as'=>'product.filter','uses'=>'ProductController@filter']);
/*    Route::get('/product/reserves',['as'=>'product.reservess','uses'=>'ProductReserveController@indddex']);*/


    Route::get('/products/reserves',['as'=>'product.reservess','uses'=>'ProductReserveController@index']);
    Route::post('/products/reserves/filter',['as'=>'product.reserves.filter','uses'=>'ProductReserveController@filter']);
    Route::get('/products/reserves/filter',['as'=>'reserves.changes','uses'=>'ProductReserveController@filter']);
    Route::post('/products/reserves/change',['as'=>'reserves.change','uses'=>'ProductReserveController@change']);


    //admin.posts controller
    Route::resource('post', 'PostController', ['except' => ['destroy']]);
    Route::Delete('/post/destroy',['as'=>'post.destroy','uses'=>'PostController@destroy']);
    Route::Post('/post/get_post_type',['as'=>'post.get_post_type','uses'=>'PostController@get_post_type']);
    Route::Post('/post/filter',['as'=>'post.filter','uses'=>'PostController@filter']);
    Route::GET('/post/create_bay_cat/{category}',['as'=>'post.create_bay_cat','uses'=>'PostController@create_bay_cat']);
    Route::GET('/post/show_bay_cat/{category}',['as'=>'post.show_bay_cat','uses'=>'PostController@show_bay_cat']);
    Route::GET('/post/create_bay_product/{product}',['as'=>'post.create_bay_product','uses'=>'PostController@create_bay_product']);
    Route::GET('/post/show_bay_product/{product}',['as'=>'post.show_bay_product','uses'=>'PostController@show_bay_product']);
    Route::GET('/post/isaac',['as'=>'post.isaac','uses'=>'PostController@isaac']);

    //admin.slider routes
    Route::resource('slider', 'SliderController', ['except' => ['destroy']]);
    Route::Delete('/slider/destroy',['as'=>'slider.destroy','uses'=>'SliderController@destroy']);
    Route::Post('/slider/get_categories',['as'=>'slider.get_categories','uses'=>'CategoryController@get_categories']);
    //admin.page routes
    Route::resource('page', 'PageController', ['except' => ['destroy']]);
    Route::Delete('/page/destroy',['as'=>'page.destroy','uses'=>'PageController@destroy']);
    Route::post('/page/slug',['as'=>'page.slug','uses'=>'pageController@slug']);


    Route::resource('article_category', 'ArticleCategoryController', ['except' => ['destroy']]);
    Route::Delete('/article_category/destroy',['as'=>'article_category.destroy','uses'=>'ArticleCategoryController@destroy']);
    Route::post('/article_category/slug',['as'=>'article_category.slug','uses'=>'ArticleCategoryController@slug']);
    Route::resource('article', 'ArticleController', ['except' => ['destroy']]);
    Route::Delete('/article/destroy',['as'=>'article.destroy','uses'=>'ArticleController@destroy']);
    Route::post('/article/slug',['as'=>'article.slug','uses'=>'ArticleController@slug']);
    Route::Post('/article/filter',['as'=>'article.filter','uses'=>'articleController@filter']);

    //admin.category routes
    Route::resource('category', 'CategoryController', ['except' => ['destroy']]);
    Route::Delete('/category/destroy',['as'=>'category.destroy','uses'=>'CategoryController@destroy']);
    Route::post('/category/slug',['as'=>'category.slug','uses'=>'CategoryController@slug']);

    //admin.menu routes
    Route::group(['prefix' => 'menu', 'as' => 'menu.'], function()
    {
        Route::get('/',['as'=>'index','uses' =>'MenuController@index']);
        Route::get('/add',['as'=>'add.show','uses' => 'MenuController@addshowfrom']);
        Route::get('/edit/{menu}',['as'=>'edit.show','uses' => 'MenuController@editshowfrom']);
        Route::post('/add',['as'=>'add','uses' => 'MenuController@add']);
        Route::delete('/delete',['as'=>'delete','uses' => 'MenuController@delete']);
        Route::patch('/edit/{menu}',['as'=>'edit','uses' => 'MenuController@edit']);
    });

    Route::group(['prefix'=>'report','as'=>'report.'],function(){
        Route::get('users',['as'=>'users','uses'=>'ReportController@user']);
        Route::post('users',['as'=>'users','uses'=>'ReportController@user']);
        Route::get('branchusers/{id}',['as'=>'branchuser','uses'=>'ReportController@branchusers']);
        Route::post('branchusers/',['as'=>'branchusers','uses'=>'ReportController@branchuser']);
        Route::get('branchusers/excelExport/{id}',['as'=>'branchers.excelExport','uses'=>'ReportController@excelExport']);

        Route::get('reserves',['as'=>'reserves','uses'=>'ReportController@reserves']);
        Route::get('site-reserves',['as'=>'site-reserves','uses'=>'ReportController@allreserves']);
        Route::post('site-reserves',['as'=>'site-reservess','uses'=>'ReportController@allreserves']);

        Route::post('seenreserve',['as'=>'seenreserve','uses'=>'ReportController@seenreserve']);

    });

    //admin.ads
    Route::resource('ads', 'AdsController', ['except' => ['destroy']]);

app/Ads.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ads extends Model
{
    protected $fillable=['title','alt','status','image','url','order'];
}

app/Http/Controllers/AdsController.php
<?php

namespace App\Http\Controllers;

use App\Ads;
use Illuminate\Http\Request;

class AdsController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
        $this->middleware('web');

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ads=Ads::all();
        return view('admin.ads.index',compact('ads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.ads.ads_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title'=>'required',
            'alt'=>'required',
            'url'=>'required',
            'order'=>'required',
            'status'=>'required',
            'image'=>'required'

        ],[
            'title.required'=>'عنوان را وارد کنید.',
            'alt.required'=>'توضیحات عکس را وارد کنید.',
            'url.required'=>'آدرس تبلیغ را وارد کنید.',
            'order.required'=>'ترتیب را وارد کنید.',
            'status.required'=>'وضعیت اجباری است',
            'image.required'=>'تصویر اجباری است.'

        ]);
        $ads=Ads::create($request->except('image'));
        $image=$request->file('image');
        $imagename=sha1($image->getClientOriginalName()).time();
        $imagemime=$image->getClientOriginalExtension();
        $name=$imagename.'.'.$imagemime;
        $image->move('images/setting/',$name);

        $ads->update(['image'=>'images/setting/'.$name]);
        flashs('تبلیغ مورد نطر افزوده شد.');
        return redirect(route('admin.ads.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ads=Ads::find($id);
        return view('admin.ads.ads_edit',compact('ads'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
       $ads=Ads::find($request->ads_id);
        $this->validate($request,[
            'title'=>'required',
            'alt'=>'required',
            'url'=>'required',
            'order'=>'required',
            'status'=>'required',
            'image'=>'required'

        ],[
            'title.required'=>'عنوان را وارد کنید.',
            'alt.required'=>'توضیحات عکس را وارد کنید.',
            'url.required'=>'آدرس تبلیغ را وارد کنید.',
            'order.required'=>'ترتیب را وارد کنید.',
            'status.required'=>'وضعیت اجباری است',
            'image.required'=>'تصویر اجباری است.'

        ]);
        $ads->update($request->except('image'));
        $image=$request->file('image');
        $imagename=sha1($image->getClientOriginalName()).time();
        $imagemime=$image->getClientOriginalExtension();
        $name=$imagename.'.'.$imagemime;
        $image->move('images/setting/',$name);

        $ads->update(['image'=>'images/setting/'.$name]);
        flashs('تبلیغ مورد نطر ویرایش شد.');
        return redirect(route('admin.ads.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ads $ads,Request $request)
    {
        $ads->destroy($request->input('selected'));
        flashs('تبلیغات پاک شدند.','success');
        return back();
    }
}

resources/views/admin/ads/ads_create.blade.php
@extends('layouts.admin_master_full')

@section('content-header')
    <section class="content-header">
        <div class="pull-left">
            <button type="submit" form="form-category" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="ذخیره"><i class="fa fa-save"></i></button>
            <a href="{{route('admin.ads.index')}}" data-toggle="tooltip" title="" class="btn btn-default" data-original-title="لغو"><i class="fa fa-reply"></i></a></div>
        <h1>
            اسلایدر جدید

        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-bars"></i> وبسایت</a></li>
            <li class="active"> جدید</li>
        </ol>
    </section>
@endsection

@section('content')

    <section class="content">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-sliders"></i>افزودن تبلیغات جدید</h3>
            </div>
            <div class="panel-body">
                <form action="{{route('admin.ads.store')}}" class="form-horizontal" method="post" enctype="multipart/form-data" id="form-category">
                    {{csrf_field()}}
                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="input-name">نام اسلایدر</label>
                        <div class="col-sm-5">
                            <input name="title" value="{{old('title')}}" placeholder="عنوان اسلایدر" id="input-name" class="form-control" type="text">
                            @if($errors->has('title'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>
               {{--     <div class="form-group">
                        <label class="col-sm-2 control-label" for="input-status">برای</label>
                        <div class="col-sm-5">
                            <select name="type_id" id="input-status" class="form-control">
                                <option value="1" selected="selected">صفحه اصلی</option>
                                <option value="2" >دسته ها</option>

                            </select>
                            @if($errors->has('type_id'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('type_id') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>--}}
                   {{-- <div class="form-group" id="resource_aria" style="display: none">
                        <label class="col-sm-2 control-label" for="input-status">دسته ی</label>
                        <div class="col-sm-5">
                            <select name="resource_id" id="input-status" class="form-control">

                            </select>
                            @if($errors->has('resource_id'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('resource_id') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>
--}}
                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="input-name">alt تبلیغ</label>
                        <div class="col-sm-5">
                            <input name="alt" value="{{old('alt')}}" placeholder="" id="input-name" class="form-control" type="text">
                            @if($errors->has('alt'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('alt') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="input-name">لینک</label>
                        <div class="col-sm-5">
                            <input name="url" value="{{old('url')}}" placeholder="" id="input-name" class="form-control" type="text">
                            @if($errors->has('url'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('url') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="input-name">ترتیب</label>
                        <div class="col-sm-5">
                            <input name="order" value="{{old('order')}}" placeholder="" id="input-name" class="form-control" type="text">
                            @if($errors->has('order'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('order') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>



                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input-status">وضعیت</label>
                        <div class="col-sm-5">
                            <select name="status" id="input-status" class="form-control">
                                <option value="1" selected="selected">فعال</option>
                                <option value="0">غیرفعال</option>
                            </select>
                            @if($errors->has('status'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="name">تصویر</label>
                        <div class="col-sm-6">
                            <input id="name" name="image" value="{{old('image')}}"  class="form-control" type="file">
                            @if ($errors->has('image'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <img src="{{url('/')}}/{{$setting->image}}" width="300" height="100">

                    </div>


                    {{--     <table id="slides" class="table table-striped table-bordered table-hover ">
                             <thead>
                             <tr>
                                 <td class="text-center">عنوان</td>
                                 <td class="text-center">لینک</td>
     --}}{{--
                                 <td class="text-center active">نوع</td>
     --}}{{--
                                 <td class="text-center">تصویر</td>
                                 <td class="text-center">ترتیب(الزامی،عددی)</td>
                                 <td class="text-center">عملیات</td>
                             </tr>
                             </thead>
                             <tbody>


                             </tbody>
                             <tfoot>
                             <tr>
                                 <td colspan="5"></td>
                                 <td class="text-left"><button type="button" onclick="addslide();" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="افزودن آگهی"><i class="fa fa-plus-circle"></i></button></td>
                             </tr>
                             </tfoot>

                         </table>
     --}}


                </form>
        {{--        <ul>
                  @if($errors->has('*'))
                        @foreach ($errors->all() as $error)
                            <li>
                                <span class="help-block"><strong>{{ $error }}</strong></span>
                            </li>

                        @endforeach
                    @endif



                </ul>--}}

            </div>
        </div>

    </section>

@endsection
@section('admin-footer')
    <script type="application/javascript">

        function readURL(input) {
            var d_id='#'+$(input).attr('d-id');
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function(e) {
                    $(d_id).attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

     /*   $('select[name=type_id]').change(function() {
            type=this.value;
            if(type==1)
            {
                $('#resource_aria').css('display','none');
                $('select[name=resource_id]').empty();
            }else if(type==2)
            {
                $('#resource_aria').css('display','block');
                $.ajax({
                    url: '{{route('admin.slider.get_categories')}}',
                    dataType: 'json',
                    type: 'POST',
                    data: {"_token":'{{csrf_token()}}'},
                    success: function(response) {
                        $('select[name=resource_id]').empty();
                        $.each(response, function(i, obj) {
                            $('select[name=resource_id]').append('<option value="'+obj.id+'">'+obj.name+'</option>');
                        });


                    },
                    error: function(x, e) {

                    }

                });
            }



        });
*/

        var image_row=0;
        function addslide() {

            html  = '<tr id="image-row' + image_row + '">';
            html += '  <td class="text-center">';
            html += '</span><input type="text" name="slide[' + image_row + '][title]" value="" placeholder="عنوان اسلاید " class="form-control" />';
            html += '  </td>';
            html += '  <td class="text-left"  width="200px"><input type="text" name="slide[' + image_row + '][link]" value="" placeholder="لینک" class="form-control text-left" /></td>';
/*
            html += '  <td class="text-left"><select name="slide['+image_row+'][btn_type]" id="btn_type'+image_row+'"> <option value="1">هیچ کدام</option><option value="2">بیشتر</option><option value="3">خرید</option></select></td>';
*/
            html += '<td class="text-center"><div class="ImageManager"><img src="{{route('home')}}/image-manager/view/1/thumb" class="imageManagerImage"><br><br><button class="fileManager btn btn-primary" type="Button" data-url="{{route('home')}}/image-manager" data-multi="false">انتخاب عکس منو</button><input class="inputFile" name="slide[' + image_row + '][image]" value="1" type="hidden"></div></td>';

            html += '  <td class="text-center"width="70px"><input type="text" name="slide[' + image_row + '][order]" value="" placeholder="ترتیب" class="form-control" /></td>';
            html += '  <td class="text-center" ><button type="button" onclick="$(\'#image-row' + image_row  + '\').remove();" data-toggle="tooltip" title="" class="btn btn-danger"><i class="fa fa-minus-circle"></i></button></td>';
            html += '</tr>';

            $('#slides tbody').append(html);

            image_row++;



            $(document).on('click', '.fileManager', function() {
                var $this = $(this);
                window.ImageManagerCaller = $this;
                $.colorbox({
                    href: $this.data('url'),
                    open: true,
                    width: '100%',
                    height: '100%',
                    onComplete: function() {
                        window.ImageManager.initPopUp();
                    }
                });
            });

        }





    </script>

@stop

resources/views/admin/ads/index.blade.php
@extends('layouts.admin_master_full')

@section('content-header')
    <section class="content-header">
        <div class="pull-left">
            <a href="{{route('admin.ads.create')}}" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="افزودن"><i class="fa fa-plus"></i></a> <a href="{{route('admin.ads.index')}}" data-toggle="tooltip" title="" class="btn btn-default" data-original-title="بازسازی"><i class="fa fa-refresh"></i></a>
            <button type="button" data-toggle="tooltip" title="" class="btn btn-danger" onclick="confirm('آیا مطمئن هستید؟') ? $('#form-category').submit() : false;" data-original-title="حذف"><i class="fa fa-trash-o"></i></button>
        </div>
        <h1>
           تبلیغات

        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> وبسایت</a></li>
            <li class="active">تبلیغات</li>
        </ol>
    </section>
@endsection

@section('content')

    <section class="content">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-list"></i> لیست تبلیغات بالای سایت </h3>
            </div>
            <form action="{{route('admin.ads.destroy')}}" method="post" enctype="multipart/form-data" id="form-category">
                {{csrf_field()}}
                {{method_field('DELETE')}}
            <div class="table-responsive">

                <table class="table table-bordered table-hover">
                    <thead>
                    <tr>
                        <td style="width: 1px;" class="text-center"><input onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" type="checkbox"></td>
                        <td class="text-center"> نام </td>
                        <td class="text-center">عکس</td>
                        <td class="text-center">لینک</td>

                        <td class="text-center">عملیات</td>
                    </tr>
                    </thead>

            <tbody>

            @foreach($ads as $a)
                    <tr>
                        <td class="text-center">
                            <input name="selected[]" value="{{$a->id}}" type="checkbox">
                        </td>
                        <td class="text-center">{{$a->title}}</td>
 <td class="text-center"><img src="{{url('/')}}/{{$a->image}}" alt="{{$a->alt}}"></td>
                        <td class="text-center">{{$a->url}}</td>
                        <td class="text-center"><a href="{{route('admin.ads.edit',$a)}}" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="ویرایش"><i class="fa fa-pencil"></i></a></td>


                    </tr>

                @endforeach
            </tbody>
                </table>

{{--
                <form action="{{route('admin.slider.destroy')}}" method="post" enctype="multipart/form-data" id="form-category">
                    {{csrf_field()}}
                    {{method_field('DELETE')}}
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <td style="width: 1px;" class="text-center"><input onclick="$('input[name*=\'selected\']').prop('checked', this.checked);" type="checkbox"></td>
                                <td class="text-center"> نام اسلایدر</td>
                                <td class="text-center">وضعیت</td>
                                <td class="text-center">عملیات</td>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($sliders as $slider )
                                <tr>
                                    <td class="text-center">
                                        <input name="selected[]" value="{{$slider->id}}" type="checkbox">
                                    </td>

                                    <td class="text-center">{{$slider->name}}</td>
                                    <td class="text-center">@if($slider->state=='0') غیرفعال @else  فعال  @endif</td>
                                    <td class="text-center"><a href="{{route('admin.slider.edit',$slider)}}" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="ویرایش"><i class="fa fa-pencil"></i></a></td>

                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                    </div>
                </form>
--}}
            </div>
            </form>
        </div>

    </section>

@endsection