routes/web.php
Route::get('/get_captcha/{config?}', function (\Mews\Captcha\Captcha $captcha, $config = 'default') {
    return $captcha->src($config);
});
/********operators routes*************/
// Authentication Routes...
Route::get('login', [
    'as' => 'login',
    'uses' => 'AuthController@login'
]);
Route::post('check_login', [
    'as' => 'check_login',
    'uses' => 'AuthController@check_login'
]);
//route::post('chech_user')

/*Route::post('login', [
    'as' => '',
    'uses' => 'Auth\LoginController@login'
]);*/
/*Route::post('logout', [
    'as' => 'logout',
    'uses' => 'AuthController@logout'
]);*/
Route::get('logout', [
    'as' => 'logout',
    'uses' => 'AuthController@logout'
]);

/*Route::get('register', [
    'as' => 'register',
    'uses' => 'AuthController@register'
]);
Route::post('register', [
    'as' => 'check_register',
    'uses' => 'AuthController@check_register'
]);*/


// Password Reset Routes...
Route::post('password/email', [
    'as' => 'password.email',
    'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail'
]);
Route::get('password/reset', [
    'as' => 'password.request',
    'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm'
]);
Route::post('password/reset', [
    'as' => '',
    'uses' => 'Auth\ResetPasswordController@reset'
]);
Route::get('password/reset/{token}', [
    'as' => 'password.reset',
    'uses' => 'Auth\ResetPasswordController@showResetForm'
]);

// Registration Routes...

/*
Route::group(['domain'=>'xbody'],function (){
    //site index route
    Route::get('/', function (){
        return view('index_page');
    })->name('home');
    Route::get('/home', 'HomeController@home')->name('home2');
    Route::get('/exchange', 'HomeController@exchange')->name('exchange');
  Route::get('/product/{product}','ProductController@show')->name('product.show');

});*/

//home routs
Route::get('/','HomeController@index')->name('home');
Route::get('page/{page}','PageController@show')->name('page');
//admin route group
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function()
{
    Route::get('/','AdminController@admin_panel')->name('admin');
    route::resource('admin','AdminController',['except'=>['destroy']]);
    Route::post('admin/socials',['as'=>'socials','uses'=>'HomeController@socials']);
    Route::post('admin/config',['as'=>'config','uses'=>'HomeController@config']);

    // Registration Routes...
    Route::get('/register',['as'=>'register','uses'=> 'AdminAuth\RegisterController@showRegistrationForm']);
    Route::post('/register',['as'=>'register','uses'=> 'AdminAuth\RegisterController@register']);
    //Login Routes...
    Route::get('/login',['as'=>'login','uses'=>'AdminAuth\LoginController@showLoginForm']);
    Route::post('/login',['as'=>'login','uses'=>'AdminAuth\LoginController@login']);
    Route::get('/logout',['as'=>'logout','uses'=>'AdminAuth\LoginController@logout']);


//admin.attribute.group routes
    Route::resource('attribute-group', 'AttributeGroupController', ['except' => ['destroy']]);
    Route::Delete('/attribute-group/destroy',['as'=>'attribute-group.destroy','uses'=>'AttributeGroupController@destroy']);
//admin.attribute routes
    Route::resource('attribute', 'AttributeController', ['except' => ['destroy']]);
    Route::Delete('/attribute/destroy',['as'=>'attribute.destroy','uses'=>'AttributeController@destroy']);

    Route::get('setting','AdminController@setting_index')->name('setting');
    Route::patch('setting','AdminController@setting')->name('setting.update');

//admin.product routes
    Route::resource('product', 'ProductController', ['except' => ['destroy']]);
    Route::Delete('/product/destroy',['as'=>'product.destroy','uses'=>'ProductController@destroy']);
    Route::post('/product/slug',['as'=>'product.slug','uses'=>'ProductController@slug']);
    Route::Post('/product/filter',['as'=>'product.filter','uses'=>'ProductController@filter']);
/*    Route::get('/product/reserves',['as'=>'product.reservess','uses'=>'ProductReserveController@indddex']);*/


    Route::get('/products/reserves',['as'=>'product.reservess','uses'=>'ProductReserveController@index']);
    Route::post('/products/reserves/filter',['as'=>'product.reserves.filter','uses'=>'ProductReserveController@filter']);
    Route::get('/products/reserves/filter',['as'=>'reserves.changes','uses'=>'ProductReserveController@filter']);
    Route::post('/products/reserves/change',['as'=>'reserves.change','uses'=>'ProductReserveController@change']);


    //admin.posts controller
    Route::resource('post', 'PostController', ['except' => ['destroy']]);
    Route::Delete('/post/destroy',['as'=>'post.destroy','uses'=>'PostController@destroy']);
    Route::Post('/post/get_post_type',['as'=>'post.get_post_type','uses'=>'PostController@get_post_type']);
    Route::Post('/post/filter',['as'=>'post.filter','uses'=>'PostController@filter']);
    Route::GET('/post/create_bay_cat/{category}',['as'=>'post.create_bay_cat','uses'=>'PostController@create_bay_cat']);
    Route::GET('/post/show_bay_cat/{category}',['as'=>'post.show_bay_cat','uses'=>'PostController@show_bay_cat']);
    Route::GET('/post/create_bay_product/{product}',['as'=>'post.create_bay_product','uses'=>'PostController@create_bay_product']);
    Route::GET('/post/show_bay_product/{product}',['as'=>'post.show_bay_product','uses'=>'PostController@show_bay_product']);
    Route::GET('/post/isaac',['as'=>'post.isaac','uses'=>'PostController@isaac']);

    //admin.slider routes
    Route::resource('slider', 'SliderController', ['except' => ['destroy']]);
    Route::Delete('/slider/destroy',['as'=>'slider.destroy','uses'=>'SliderController@destroy']);
    Route::Post('/slider/get_categories',['as'=>'slider.get_categories','uses'=>'CategoryController@get_categories']);
    //admin.page routes
    Route::resource('page', 'PageController', ['except' => ['destroy']]);
    Route::Delete('/page/destroy',['as'=>'page.destroy','uses'=>'PageController@destroy']);
    Route::post('/page/slug',['as'=>'page.slug','uses'=>'pageController@slug']);


    Route::resource('article_category', 'ArticleCategoryController', ['except' => ['destroy']]);
    Route::Delete('/article_category/destroy',['as'=>'article_category.destroy','uses'=>'ArticleCategoryController@destroy']);
    Route::post('/article_category/slug',['as'=>'article_category.slug','uses'=>'ArticleCategoryController@slug']);
    Route::resource('article', 'ArticleController', ['except' => ['destroy']]);
    Route::Delete('/article/destroy',['as'=>'article.destroy','uses'=>'ArticleController@destroy']);
    Route::post('/article/slug',['as'=>'article.slug','uses'=>'ArticleController@slug']);
    Route::Post('/article/filter',['as'=>'article.filter','uses'=>'articleController@filter']);

    //admin.category routes
    Route::resource('category', 'CategoryController', ['except' => ['destroy']]);
    Route::Delete('/category/destroy',['as'=>'category.destroy','uses'=>'CategoryController@destroy']);
    Route::post('/category/slug',['as'=>'category.slug','uses'=>'CategoryController@slug']);

    //admin.menu routes
    Route::group(['prefix' => 'menu', 'as' => 'menu.'], function()
    {
        Route::get('/',['as'=>'index','uses' =>'MenuController@index']);
        Route::get('/add',['as'=>'add.show','uses' => 'MenuController@addshowfrom']);
        Route::get('/edit/{menu}',['as'=>'edit.show','uses' => 'MenuController@editshowfrom']);
        Route::post('/add',['as'=>'add','uses' => 'MenuController@add']);
        Route::delete('/delete',['as'=>'delete','uses' => 'MenuController@delete']);
        Route::patch('/edit/{menu}',['as'=>'edit','uses' => 'MenuController@edit']);
    });

    Route::group(['prefix'=>'report','as'=>'report.'],function(){
        Route::get('users',['as'=>'users','uses'=>'ReportController@user']);
        Route::post('users',['as'=>'users','uses'=>'ReportController@user']);
        Route::get('branchusers/{id}',['as'=>'branchuser','uses'=>'ReportController@branchusers']);
        Route::post('branchusers/',['as'=>'branchusers','uses'=>'ReportController@branchuser']);
        Route::get('branchusers/excelExport/{id}',['as'=>'branchers.excelExport','uses'=>'ReportController@excelExport']);

        Route::get('reserves',['as'=>'reserves','uses'=>'ReportController@reserves']);
        Route::get('site-reserves',['as'=>'site-reserves','uses'=>'ReportController@allreserves']);
        Route::post('site-reserves',['as'=>'site-reservess','uses'=>'ReportController@allreserves']);

        Route::post('seenreserve',['as'=>'seenreserve','uses'=>'ReportController@seenreserve']);

    });

    //admin.ads
    Route::resource('ads', 'AdsController', ['except' => ['destroy']]);
    Route::Delete('/ads/destroy',['as'=>'ads.destroy','uses'=>'AdsController@destroy']);


    /*Branches routes*/
    Route::delete('branches/destroy',['as'=>'branches.destroy','uses'=>'BranchesController@destroy']);
    Route::resource('branches' , 'BranchesController' ,['except'=>['destroy']]);

    /*admin message Routes*/
    Route::get('message/delete/{id}' , 'MessageController@destroy')->name('message.delete');
    Route::post('message/changeStatus' , 'MessageController@changeStatus')->name('message.changeStatus');
    Route::resource('message' , 'MessageController' ,['except' => ['destroy']]);

    /*admin gallery routes*/
    Route::get('gallery/changeStatus/{gallery}' , 'GalleryController@changeStatus')->name('gallery.changeStatus');
    Route::post('/gallery/destroy' , 'GalleryController@destroy')->name('gallery.destroy');
    Route::post('/gallery/storeValidation' , 'GalleryController@store_validation')->name('gallery.store_validation');
    Route::get('gallery/deleteVideoFromGallery/{gallery}/{video}' , ['as'=>'gallery.delete_video_from_gallery' , 'uses' => 'GalleryController@deleteVideoFromGallery']);
    Route::post('gallery/videos/addVideoToGallery/{gallery}' , 'GalleryController@addVideo')->name('gallery.video.add_video');

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $fillable=['logo','facebook','instagram','telegram','product_header','product_des'];
}

resources/views/admin/setting/setting_add.blade.php
@extends('layouts.admin_master_full')

@section('content-header')
    <section class="content-header">
        <div class="pull-left">
            <button type="submit" form="form-category" data-toggle="tooltip" title="" class="btn btn-primary" data-original-title="ذخیره"><i class="fa fa-save"></i></button>
            <a href="/admin/menu" data-toggle="tooltip" title="" class="btn btn-default" data-original-title="لغو"><i class="fa fa-reply"></i></a></div>
        <h1>
           تنظیمات سایت

        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-bars"></i> وبسایت</a></li>
            <li class="active">تنظیمات سایت</li>
        </ol>
    </section>
@endsection

@section('content')

    <section class="content">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-plus "></i>تنظیمات سایت</h3>
            </div>
            <div class="panel-body">
                <form action="{{route('admin.setting.update')}}" class="form-horizontal" method="post" enctype="multipart/form-data" id="form-category">
                    {{csrf_field()}}
{{method_field('PATCH')}}
                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="name">لوگو</label>
                        <div class="col-sm-6">
                            <input id="name" name="logo" value="{{old('logo')}}"  class="form-control" type="file">
                            @if ($errors->has('logo'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('logo') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <img src="{{url('/')}}/{{$setting->logo}}" width="300" height="100">

                    </div>

                   {{-- <div class="form-group required">
                        <label class="col-sm-2 control-label" for="name">تبلیغ بالای سایت</label>
                        <div class="col-sm-6">
                            <input id="ads" name="ads" value="{{old('ads')}}"  class="form-control" type="file">
                            @if ($errors->has('ads'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('ads') }}</strong>
                                    </span>
                            @endif
                        </div>
                        <img src="{{url('/')}}/{{$setting->ads}}" class="center-block">

                    </div>--}}

                   {{-- <div class="form-group required">
                        <label class="col-sm-2 control-label" for="link">لینک عکس تبلیغ</label>
                        <div class="col-sm-8">
                            <input name="ads_url" value="{{$setting->ads_url}}" placeholder="http://xbody.com" id="link" class="form-control text-left" style="direction: ltr;" type="text">
                            @if ($errors->has('ads_url'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('ads_url') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>
--}}
                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="link">عنوان صفحه محصول</label>
                        <div class="col-sm-8">
                            <input name="product_header" value="{{$setting->product_header}}" placeholder="" id="link" class="form-control text-left" style="direction: ltr;" type="text">
                            @if ($errors->has('product_header'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('product_header') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="link">متن صفحه محصول</label>
                        <div class="col-sm-8">
                            <textarea name="product_des"  placeholder="{{$setting->product_des}}" id="link" class="form-control text-left" style="direction: ltr;" type="text">{{$setting->product_des}}</textarea>
                            @if ($errors->has('product_des'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('product_des') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="link">آی دی فیس بوک</label>
                            <div class="col-sm-8">
                                <input name="facebook" value="{{$setting->facebook}}" placeholder="xbody" id="link" class="form-control text-left" style="direction: ltr;" type="text">
                                @if ($errors->has('facebook'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('facebook') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="link">آی دی تلگرام</label>
                        <div class="col-sm-8">
                            <input name="telegram" value="{{$setting->telegram}}" placeholder="xbody" id="link" class="form-control text-left" style="direction: ltr;" type="text">
                            @if ($errors->has('telegram'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('telegram') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group required">
                        <label class="col-sm-2 control-label" for="link">آی دی اینستاگرام</label>
                        <div class="col-sm-8">
                            <input name="instagram" value="{{$setting->instagram}}" placeholder="xbody" id="link" class="form-control text-left" style="direction: ltr;" type="text">
                            @if ($errors->has('instagram'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('instagram') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>


</form>

</div>
</div>

</section>

@endsection